### PR TITLE
Compilation Fixes

### PR DESCRIPTION
**Pull request by Lonely-Dark**
I fix a compilation issue. Now, compiling for twrp is successful

### CODE REVIEW

**Comment by Imshubh69** [comment]
@Lonely-Dark is it booted?

**Comment by Lonely-Dark** [comment]
@Imshubh69 Yep, but data is 0mb

**Comment by Lonely-Dark** [comment]
Issue with encryption

**Comment by Imshubh69** [comment]
> Issue with encryption

Nice i will fix it don't worry about it

**Comment by Imshubh69** [comment]
Thanks @Lonely-Dark for patches

**Pull request merged**
